# general settings
name: train_OMGAN_Mask_HLIP
model_type: OMGANModel
scale: 1
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: MultiMask
    type: MultiMaskImageDataset
    dataroot_path: datasets/HLIP_train_name.txt
    io_backend:
      type: meta_info_file

    gt_size: 256
    mean: 0.5
    std: 0.5
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 64
    prefetch_mode: ~



# network structures
network_g:
  type: UnetGenerator
  input_nc: 3
  output_nc: 6 
  num_downs: 8
  ngf: 64
  norm_type: instance
  use_dropout: True
  use_attention: True

network_d:
  type: PatchDiscriminator
  input_nc: 3
  ndf: 64
  n_layers: 3

# path
path:
  pretrain_network_g: experiments/train_OM_Mask_HLIP/models/net_g_latest.pth
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~
  

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [10000]
    gamma: 0.5

  total_iter: 10000
  warmup_iter: -1  # no warm up

# losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0



# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
# dist training settings
dist_params:
  backend: nccl
  port: 29501
